export const users = [
  {
    "id": 0,
    "username": "admin",
    "passcode": "000000",
    "age": 35,
    "gender": "N/A",
    "occupation": "System Administrator",
    "location": "Mumbai, Maharashtra",
    "reasonForUse": "System Testing",
  },
  {
    "id": 101,
    "username": "Rohan_S",
    "passcode": "112233",
    "age": 19,
    "gender": "Male",
    "occupation": "College Student",
    "location": "Mumbai, Maharashtra",
    "reasonForUse": "Exam stress",
  },
  {
    "id": 102,
    "username": "Priya_K",
    "passcode": "987654",
    "age": 28,
    "gender": "Female",
    "occupation": "Software Engineer",
    "location": "Bengaluru, Karnataka",
    "reasonForUse": "Work-life balance",
  },
  {
    "id": 103,
    "username": "Aarav_J",
    "passcode": "258025",
    "age": 34,
    "gender": "Male",
    "occupation": "Graphic Designer",
    "location": "Delhi",
    "reasonForUse": "Creative block & anxiety",
  },
  {
    "id": 104,
    "username": "Sunita_M",
    "passcode": "555555",
    "age": 45,
    "gender": "Female",
    "occupation": "Homemaker",
    "location": "Kolkata, West Bengal",
    "reasonForUse": "Loneliness",
  },
  {
    "id": 105,
    "username": "Vikram_C",
    "passcode": "432100",
    "age": 25,
    "gender": "Male",
    "occupation": "Freelance Writer",
    "location": "Pune, Maharashtra",
    "reasonForUse": "Financial stress",
  },
  {
    "id": 106,
    "username": "Ananya_R",
    "passcode": "200211",
    "age": 22,
    "gender": "Female",
    "occupation": "Medical Student",
    "location": "Chennai, Tamil Nadu",
    "reasonForUse": "Academic pressure",
  },
  {
    "id": 107,
    "username": "Kabeer_D",
    "passcode": "770088",
    "age": 38,
    "gender": "Male",
    "occupation": "Startup Founder",
    "location": "Hyderabad, Telangana",
    "reasonForUse": "Managing burnout",
  },
  {
    "id": 108,
    "username": "Ishaan",
    "passcode": "131313",
    "age": 20,
    "gender": "Non-binary",
    "occupation": "University Student",
    "location": "Goa",
    "reasonForUse": "Self-discovery",
  },
  {
    "id": 109,
    "username": "Mr_Sharma",
    "passcode": "195867",
    "age": 67,
    "gender": "Male",
    "occupation": "Retired",
    "location": "Jaipur, Rajasthan",
    "reasonForUse": "Feeling isolated",
  },
  {
    "id": 110,
    "username": "Dr_Fatima",
    "passcode": "313131",
    "age": 31,
    "gender": "Female",
    "occupation": "Doctor",
    "location": "Mumbai, Maharashtra",
    "reasonForUse": "Professional stress",
  }
]